ARC: testsuite fix: conform/POSIX/signal.h/conform
  Testing for member sa_flags... OK
  Testing for type of member sa_flags... FAIL
    Member "sa_flags" does not have the correct type.  Compiler message:
    -----------------------------------------------------------------------
    build/conform/POSIX/signal.h/scratch/signal.h-test.c:4:32: error: conflicting types for 'b'
     extern __typeof__ (a.sa_flags) b;
                                    ^
    build/conform/POSIX/signal.h/scratch/signal.h-test.c:3:12: note: previous declaration of 'b' was here
     extern int b;
                ^
    -----------------------------------------------------------------------

Signed-off-by: Vineet Gupta <vgupta@synopsys.com>